### PR TITLE
Add exampleSite

### LINKED ISSUE #35: Provide an exampleSite
see #30 
PR Welcome

### PR DESCRIPTION
**Pull request by UtkarshVerma**
Fixes #35 .

### CODE REVIEW

**Comment by humboldtux** [comment]
Hello, i don't maintain this repo anymore, i can transfer it to you if you want.

**Comment by UtkarshVerma** [comment]
@humboldtux You may transfer it.

**Comment by humboldtux** [comment]
I have never done a transfer: do you know how to do that? Do you have a
link to a GitHub help page? Should i just add you to the admin member group
of the repo?

thanks

--
@humboldtux


Le mer. 3 oct. 2018 à 10:09, Utkarsh Verma <notifications@github.com> a
écrit :

**Comment by UtkarshVerma** [comment]
@humboldtux Here it is: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by UtkarshVerma** [comment]
I've renamed it.

**Comment by humboldtux** [comment]
I still can't transfer it, GitHub is still complaining  you already have
a startbootstrap-clean-blog repo
Maybe renaming is not enough, because internally it kep the old name, you
may need to delete it

--
@humboldtux


Le sam. 6 oct. 2018 à 03:29, Utkarsh Verma <notifications@github.com> a
écrit :

**Comment by UtkarshVerma** [comment]
Ok I'll delete it by tomorrow, after backing up a clone

**Comment by UtkarshVerma** [comment]
Done! You're welcome.

**Pull request merged**
