### PR TITLE
Always load assets over HTTPS

### PR DESCRIPTION
**Pull request by coliff**

### CODE REVIEW

**Comment by coliff** [comment]
@UtkarshVerma  - could you merge this one?

**Comment by UtkarshVerma** [comment]
@coliff Sorry for the delay. This had gotten off my mind.

**Comment by coliff** [comment]
no problem :-) I'll help you to keep it up-to-date and open a few more PRs

**Comment by UtkarshVerma** [comment]
Thanks, I appreciate that a lot. I currently have my hands full with another project. I hope I'll be able to work on this theme soon.

**Pull request merged**
